import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Layout, { Content, Footer, Header } from "antd/es/layout/layout";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerStyle: React.CSSProperties = {
    height: 64,
    backgroundColor: '#4096ff',
  };

      const contentStyle: React.CSSProperties = {
    minHeight: 'calc(100vh - 64px)',
  };

  const layoutStyle = {
  };
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > <Layout style={layoutStyle}>
          <Header style={headerStyle}>Header</Header>
          <Content style={contentStyle}>{children}</Content>
          {/* <Footer style={footerStyle}>Footer</Footer> */}
        </Layout>

      </body>
    </html>
  );
}
